# Generated by Django 4.1.4 on 2023-03-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
